[project]
name = "repl-nix-weatherweb"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "pytz>=2024.2",
    "requests>=2.32.3",
]
